from enum import Enum


class CharStats(Enum):
	HP = 1
	HPP = 2
	DEFP = 3
	DEF = 4
	ATK = 5
	ATKP = 6
	ER = 7
	EM = 8
	CRIT_RATE = 9
	CRIT_DMG = 10
	HEALING_BONUS = 11
	PYRO_DMG_BONUS = 12
	HYDRO_DMG_BONUS = 13
	CRYO_DMG_BONUS = 14
	ELECTRO_DMG_BONUS = 15
	ANEMO_DMG_BONUS = 16
	GEO_DMG_BONUS = 17
	DENDRO_DMG_BONUS = 18
	PHYSICAL_DMG_BONUS = 19
	ATTACK_SPD = 20
	ALL_DMG_BONUS = 21
	BASE_HP = 22
	BASE_ATK = 23
	BASE_DEF = 24