from enum import Enum


class ICDTag(Enum):
    NONE = 0
    NORMAL_ATTACK = 1
    EXTRA_ATTACK = 2
    ELEMENTAL_ART = 3
    ELEMENTAL_ART_HOLD = 4
    ELEMENTAL_ART_ANEMO = 5
    ELEMENTAL_ART_PYRO = 6
    ELEMENTAL_ART_HYDRO = 7
    ELEMENTAL_ART_CRYO = 8
    ELEMENTAL_ART_ELECTRO = 9
    ELEMENTAL_BURST = 10
    ELEMENTAL_BURST_ANEMO = 11
    ELEMENTAL_BURST_PYRO = 12
    ELEMENTAL_BURST_HYDRO = 13
    ELEMENTAL_BURST_CRYO = 14
    ELEMENTAL_BURST_ELECTRO = 15
    DASH = 16
    TRAVELER_WAKE_OF_EARTH = 17
    TRAVELER_DEWDROP = 18
    OVERLOAD_DAMAGE = 19
    SUPERCONDUCT_DAMAGE = 20
    EC_DAMAGE = 21
    SHATTER = 22
    SWIRL_PYRO = 23
    SWIRL_HYDRO = 24
    SWIRL_CRYO = 25
    SWIRL_ELECTRO = 26
    BURNING_DAMAGE = 27
    BLOOM_DAMAGE = 28
    BOUNTIFUL_CORE_DAMAGE = 29
    BURGEON_DAMAGE = 30
    HYPERBLOOM_DAMAGE = 31

class ICDGroup(Enum):
    DEFAULT = 0
    POLE_EXTRA_ATTACK = 1
    REACTION_A = 2
    REACTION_B = 3
    BURNING = 4
    TRAVELER_DEWDROP = 5
    TRAVELER_BURST = 6