from enum import Enum


class CharacterStats(Enum):
    HP = 1
    ATK = 2
    DEF = 3
    ELEMENTAL_MASTERY = 4
    ENERGY_RECHARGE = 5
    CRIT_RATE = 6
    CRIT_DMG = 7
    ALL_DMG_BONUS = 8
    PYRO_DMG_BONUS = 9
    HYDRO_DMG_BONUS = 10
    ELECTRO_DMG_BONUS = 11
    ANEMO_DMG_BONUS = 12
    GEO_DMG_BONUS = 13
    DENDRO_DMG_BONUS = 14
    PHYSICAL_DMG_BONUS = 15
    CRYO_DMG_BONUS = 16
    NORMAL_ATTACK_DMG_BONUS = 17
    CHARGED_ATTACK_DMG_BONUS = 18
    PLUNGE_ATTACK_DMG_BONUS = 19
    ELEMENTAL_SKILL_DMG_BONUS = 18
    ELEMENTAL_BURST_DMG_BONUS = 20
    HEALING_BONUS = 21
    HEALING_RECEIVED_BONUS = 22
    SHIELD_STRENGTH = 23
    ANEMO_RES = 24
    PYRO_RES = 25
    HYDRO_RES = 26
    ELECTRO_RES = 27
    CRYO_RES = 28
    GEO_RES = 29
    DENDRO_RES = 30
    PHYSICAL_RES = 31
    NORMAL_ATTACK_CRIT_RATE_BONUS = 32
    NORMAL_ATTACK_CRIT_DMG_BONUS = 33
    CHARGED_ATTACK_CRIT_RATE_BONUS = 34
    CHARGED_ATTACK_CRIT_DMG_BONUS = 35
    PLUNGE_ATTACK_CRIT_RATE_BONUS = 36
    PLUNGE_ATTACK_CRIT_DMG_BONUS = 37
    ELEMENTAL_SKILL_CRIT_RATE_BONUS = 38
    ELEMENTAL_SKILL_CRIT_DMG_BONUS = 39
    ELEMENTAL_BURST_CRIT_RATE_BONUS = 40
    ELEMENTAL_BURST_CRIT_DMG_BONUS = 41
    HP_PERCENTAGE = 42
    ATK_PERCENTAGE = 43
    DEF_PERCENTAGE = 44

class ReactionBonusStats(Enum):
    SWIRL_DMG_BONUS = 1
    OVERLOAD_DMG_BONUS = 2
    ELECTRO_CHARGED_DMG_BONUS = 3
    MELT_DMG_BONUS = 4
    VAPORIZE_DMG_BONUS = 5
    SHATTER_DMG_BONUS = 6
    BURNING_DMG_BONUS = 7
    AGGRAVATE_DMG_BONUS = 8
    SPREAD_DMG_BONUS = 9
    BLOOM_DMG_BONUS = 10
    BURGEON_DMG_BONUS = 11
    HYPERBLOOM_DMG_BONUS = 12

class ScalingStats(Enum):
    HP_PERCENTAGE = 1
    ATK_PERCENTAGE = 2
    DEF_PERCENTAGE = 3